### ISSUE TITLE
App creates new folder

### ISSUE THREAD

**Issue by ghost** [neil-morrison44/pocket-sync#149]
The app creates the folder "jtpatreon" everytime i go to the GAMES tab. 

<img width="1032" alt="Bildschirmfoto 2023-09-22 um 19 00 50" src="https://github.com/neil-morrison44/pocket-sync/assets/32906058/1dec51b8-7033-4603-9a79-089cb22320ab">
<img width="1191" alt="Bildschirmfoto 2023-09-22 um 18 58 38" src="https://github.com/neil-morrison44/pocket-sync/assets/32906058/690869c1-3ac5-4558-af10-bbdc8204aac0">

**Comment by neil-morrison44** [comment]
Is this causing an issue or is it just a bit weird?

JOTEGO has said that that folder’ll be the final location of the JTBETA file once Analogue release a firmware update that’ll let all his cores read from it there.

I think the behaviour is right - it won’t be created as part of the zip install flow since it’s an empty folder but is a place that games could (theoretically) be.

**Comment by neogeo81** [comment]
It's weird. It creates double folders which are empty. Look at the second screenshot

**Comment by neil-morrison44** [comment]
They’re technically not double folders - it’s saying that multiple cores point at the same location for games. Agree it’s weird though.

If the `platform_id` was being used for a what I assume is its original purpose (splitting things up like Mega Drive / Genesis, Famicom / NES) it’d make more sense.

Each core _could_ have its own folder within the shared platform folder too so it’s not possible to de-dupe them into one (and it’d need to list all the cores which apply to it).


If Analogue change the format of the data.json file to make it more explicit which files come from where it’ll be possible to clean this up, but until then I think this is probably the best it can get while supporting everything.
