### ISSUE TITLE
Make it possible to download only select "required files"

### ISSUE THREAD

**Issue by hadess** [neil-morrison44/pocket-sync#174]
Clicking the "required files" button for a core requires downloading all the files:
![image](https://github.com/neil-morrison44/pocket-sync/assets/769861/89950fe8-cff7-456e-ae81-6afd0daad570)

It would be useful to be able to differentiate required from optional files, to avoid encumbering the Pocket's game list.

**Comment by neil-morrison44** [comment]
I think this is a won’t fix, I’ve considered it in the past but I couldn’t work out a nice way to have the Pocket not show the non-installed files (since their JSONs will already exist & need to exist so Pocket Sync can show the option & moving them will just result in duplicates once the core updates).

The result would be users getting confused when they forget which they’ve actually installed.

The `_alternatives` folder was put in so that users don’t have to install _every_ version, and there’s a clear enough separation on the device itself.

The upcoming “Fast Downloads” option should make it less laborious to download all the files
