### ISSUE TITLE
User interface is not updating after an operation

### ISSUE THREAD

**Issue by mjsztainbok** [neil-morrison44/pocket-sync#214]
**Describe the bug**
I installed 4.1.0 and since then whenever I do any operations (e.g change a setting, download required files, change a name or image using a data or image pack, etc.) the user interface is not updating to show the change.

**To Reproduce**
Steps to reproduce the behaviour (one example):
1. Go Cores
2. Click on any core which doesn't have required files
3. Download the required files
4. The user interface still shows the required files not downloaded and clicking on it shows the files as Downloadable even though they are downloaded

If the error only appeared after installing a certain core or image pack say which one.

**Expected behaviour**
The user interface is updated with the change that was just made

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - 11

**Additional context**
None

**Comment by neil-morrison44** [comment]
I was expecting a lot more of this sort of issue with 4.1.0 & I’m surprised it’s just you (so far anyway):

- how is it you’re mounting the pocket? USB or SD Card?
- What’s the drive letter of your Pocket?

It works for me on Windows 11 & (I’m assuming) works for others, but this is exactly the sort of issue the changes in 4.1.0 would cause since I redid all the filesystem stuff to be notification based & if the notifications aren’t triggering for some reason then that’s what you’d see.

**Comment by mjsztainbok** [comment]
I'm using a microSD card adapter in my laptop's SD card slot and it's drive letter is F:

**Comment by neil-morrison44** [comment]
Hmmm, yeah that matches my Windows 11 setup pretty closely.

There’s one thing that could shed some light on it - if you run the app from the `cmd` prompt (e.g `start path/to/pocket sync.exe`) you might get a good error message out of it.

**Comment by mjsztainbok** [comment]
I tried running it from the console and didn't see any output

**Comment by crazybingo123** [comment]
Also getting the same issue. Same setup, trying to use with W11 and SD card. CMD did not give me any output

**Comment by neil-morrison44** [comment]
My thoughts on this are:
There's been 1,097 windows downloads of 4.1 so far & if it was a widespread issue I'd have expected a _lot_ of issues - but if it's happening to two of you then there's probably at least 18 more who haven't raised GitHub issues.

Hopefully more people with the issue find this and there's some sort of commonality between the setups that differs from working.

Do you know what filesystem format (eg. FAT, ExFAT, etc) you're using? Both on the SD card & Windows itself?


Failing that, I could put an option in the settings to not use the new filesystem stuff & instead manually refresh based on what files the app knows it's changed. There would be a decent amount of work involved in that though, so ideally it's something simple.

**Comment by mjsztainbok** [comment]
My microSD card is exFat and my Windows drive is NTFS

**Comment by Condemned87** [comment]
I have also issues since the last update. Going to Cores, selecting the new budude2 gb core, click on download - the pocket sync screen goes grey, nothing else. Have to close the program and restart pocket sync, the files were not downloaded. This is reproductable every time. Its not working anymore. (also on windows 11, if important)

**Comment by neil-morrison44** [comment]
@Condemned87 think that’s probably a different issue, completely grey or grey with loading spinner?

**Comment by Condemned87** [comment]
Completely grey. At beginning pocket sync shows the analogue pocket with 0% and right after 6% was shown the screen went completely grey and thats it. This happenend every time I try to download a core. Before 4.10 it works perfectly.

**Comment by neil-morrison44** [comment]
@Condemned87 if you're still seeing that after you've updated to v4.2 (which'll probably be out later today) then do you mind opening a new issue for it? They're definitely related since they're both caused by the only change to go into v4.1 - but I'm not sure the fix that'll go into v4.2 will fix what you were seeing

**Comment by Condemned87** [comment]
Yes I will. Thank you :)
