### ISSUE TITLE
Jotego Core Updates Are Wanting to Update to Older Commits

### ISSUE THREAD

**Issue by 32gits** [neil-morrison44/pocket-sync#266]
**Describe the bug**
When viewing core updates, all of the Jotego cores are suggesting updates from [2ff66e2](https://github.com/jotego/jtcores/commit/2ff66e28b50a027db1a540e2641e94d9ddd71f43) to [7e16d43](https://github.com/jotego/jtcores/commit/7e16d4398cd88c8276a81cc6c94bcd8939e169f2)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Cores tab
2. View the Jotego Cores and compare installed commit ID versus suggested update commit ID

If the error only appeared after installing a certain core or image pack say which one.

**Expected behaviour**
Updates should be for newer commits

**Screenshots**
![image](https://github.com/neil-morrison44/pocket-sync/assets/10841727/b4fac78f-e216-414c-8abd-91c8eb67542e)
![image](https://github.com/neil-morrison44/pocket-sync/assets/10841727/d7e9c490-3435-44ed-86fc-3b58535a9179)
![image](https://github.com/neil-morrison44/pocket-sync/assets/10841727/69aa682f-52f5-42d4-b05d-51653fdb81c1)

**Logs**
[Pocket Sync.log](https://github.com/neil-morrison44/pocket-sync/files/14936108/Pocket.Sync.log)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version: Pocket Sync 4.7.0

**Comment by neil-morrison44** [comment]
There’s a couple of things this could be:
- The JOTEGO script which builds the zips uses the commit hash from the most recently changed file within the zip rather than the most recent one for the whole repo (to avoid updates without changes).
- If the zip that’s in the JOTEGO repo has been rebuilt with the more recent commit hash, then it could be the inventory failing to pick it up, but it’s not had issues with that previously to my knowledge.
- If it is a real update & the inventory is showing the more recent commit then, considering that the inventory API’s what tells all the updaters what the latest version is, Pocket Sync might have fallen behind it  which would fix itself on a restart (and I believe this was an issue previously but I fixed it)

**Comment by neil-morrison44** [comment]
Yeah, looks like there’s not been any updates to the actual raw files either in the 2ff commit or since then.

Also, I’m not sure why, but the workflow to automate creation of the zips has been changed to be manual only: https://github.com/jotego/jtbin/commit/dd055d550c76dc8ff4219a573e4dfb8127cd88a5

So this might be an issue you have to check with JOTEGO.

Going to close this since it seems to be upstream of Pocket Sync - feel free to reopen if it turns out the new cores have been released as usual

**Comment by neil-morrison44** [comment]
Looks like it might be the inventory - it lists jt1942 version `7e16d43` as the latest

https://openfpga-cores-inventory.github.io/analogue-pocket/

Definitely something weird going on, but Pocket Sync seems to be doing what it’s told at least…
