### ISSUE TITLE
Doesn't work on macOS 11.7.10

### ISSUE THREAD

**Issue by kotbayun** [neil-morrison44/pocket-sync#337]
Continues not to work on my macOS 11.7.10
This problem appeared with version 5.0 and continues to be on 5.2.0

Just a gray application window with no text on startup.
!![Снимок экрана 2024-10-14 в 11 52 53](https://github.com/user-attachments/assets/524ae202-c385-40a5-aea4-5cc9639f4ed6)

**Comment by neil-morrison44** [comment]
macOS 11 is now 5 versions behind the latest version - I only aim to support the most recent 2 versions (due to the way Tauri uses the system Webkit installation).

To fix a macOS 11 user would need to boot the app in developer mode & find the error (there's some fixes for macOS 12 which went in via that).

I'm closing the macOS 11 issues since it's outside of the window I can support
