### ISSUE TITLE
Feature request: allow selecting multiple screenshots to save

### ISSUE THREAD

**Issue by akira28** [neil-morrison44/pocket-sync#38]
I use screenshots a lot (playing with my Gameboy Camera since I got the Analogue). It would be super nice to be able to select multiple screenshots and save them in just one go, instead of having to open each one.

**Comment by neil-morrison44** [comment]
Definitely something I'll have a think about at some point - currently everything's set up pretty asynchronously so it only loads the info needed to correct the raw screenshot etc when you click in to it.

Multi-screenshot selection would be useful even just for bulk deleting them, and once that's in it'd be _reasonably_ simple to throw up a new modal for bulk save.

**Comment by SpookySquidGames** [comment]
Seconding bulk screenshot exporting being a really useful feature! Related to that having the option to automatically name the saved image files using the game's name instead of just Analogue's vague date based naming convention would be really helpful. Alternately putting them into sub-directories based on the game's name would also work. Otherwise if you're bulk exporting a large number of screenshots from different games you'll end up with a big mess to sort through by hand after.
