### ISSUE TITLE
Consider using the .token file in the root, if it exists, for authenticated GitHub API calls

### ISSUE THREAD

**Issue by shanselman** [neil-morrison44/pocket-sync#40]
Some Pocket utilities use a .token file (if it exists) in the root of the SD Card. If you checked for that and added it to GitHub API calls it would unblock folks who are rate limited.

**Comment by neil-morrison44** [comment]
What's the usage pattern in Pocket Sync that goes over the rate limit? I've never gone over it while testing locally but this is the 2nd issue today mentioning it so that's a bit weird.

My goal was to keep it far under the limit & thus not have a better experience for folks with github accounts - I'll recheck that the requests are as few as they can be first then have a look into reusing the `.token`

**Comment by shanselman** [comment]
I think it's folks, like myself, who got their Analogues and "dove right in" so I ran a powershell script to get some cores, and all that content is on GitHub, so when I got around to finding PocketSync, I'd used up my spoons. So, in the case of the PowerShell downloader, I noted and generated a .token file https://github.com/KeenIIDX/openFPGAUpdater/blob/main/openFpgaUpdater.ps1#L5

**Comment by neil-morrison44** [comment]
Ah yeah - there's enough cores that those scripts will pretty much always cause the limit to be hit just now (but soon the inventory'll contain the raw url for the zip file which should fix that)

The error from Pocket Sync should definitely be clearer about what's happened but outside of using it just after loading cores from elsewhere I think it's pretty much impossible to hit the limit solely through using Pocket Sync so the token file's probably of limited usage (and even then there's still a rate limit to the PAT token requests which, hopefully, there's enough cores to hit some day)
