### ISSUE TITLE
Check for core/firmware updates without connected Pocket?

### ISSUE THREAD

**Issue by epochVHS** [neil-morrison44/pocket-sync#56]
As someone who has converted to using Pocket Sync exclusively, I was wondering if there was a way that Pocket Sync could "remember" which core versions/firmware are installed on a specific Pocket and let you know if there are updates available without connecting the Pocket or the memory card?
(I'm aware firmware updates aren't supported yet, but just for completeness' sake)

**Comment by neil-morrison44** [comment]
By “on a specific Pocket” do you mean you’re using it to update more than 1 Pocket?

There’s a longer term plan to have the inventory API deliver some sort of “news” feed which pocket sync will listen to in the background (with optional notifications) so it could list off all the updates / new cores etc that have happened since the last time you connected a Pocket but that’s probably a while away

for anything to do with firmware the files on the Pocket’s SD card only knows it’s on 1.1 (and not anything about which beta it’s on) so I’m hoping that changes once 1.1 is released properly then we’ll see what can be done

**Comment by epochVHS** [comment]
No, just one pocket. And I don't think many people are using more than one, I just mean the last Pocket the app saw, or something along those lines.

The CLI updater pocket_updater seems to check on firmware upgrades by recording which Pocket firmware update has been downloaded last and seeing if there's a new one, for what it's worth.

That long term plan sounds great actually-similar to what I'm suggesting-I guess "since last time" is also a reasonable metric. Thanks for all your effort!

**Comment by evie-gh** [comment]
my solution to this was copying my Pocket file system to a local folder on my PC, and using pocket-sync to manage this folder directly. I then use rsync to deploy to my Pocket whenever I want to update, and copy saves back as needed for backup. maybe this would work for you?
