### ISSUE TITLE
Pocket - Sync Won't Open on Catalina

### ISSUE THREAD

**Issue by jurkevicz** [neil-morrison44/pocket-sync#72]
my MacBook air is running Catalina 10.15.7 and 
the latest pocket sync update just open a blank window.
Previous Version was working perfectly.

**Comment by neil-morrison44** [comment]
What was the version number of the build that was working?

**Comment by jurkevicz** [comment]
I was using version 2.2.1 with no issues.

Sent from my iPhone

On Jan 30, 2023, at 12:28 PM, Neil Morrison ***@***.***> wrote:

﻿

What was the version number of the build that was working?

**Comment by neil-morrison44** [comment]
I didn't think it'd be working on anything before Monterey / Big Sur so that's interesting...

I've had a look over all the changes between that version and the current version & nothing I've changed seems like it's break this (but it could be an incompatible dependency that's been updated).

I can't test on older versions of MacOS & the way the app's build makes it reliant on the version of Safari baked into the OS since Apple don't keep that up to date.

So, sorry, but there's not a whole lot I can do - there's nothing coming soon API wise (I think) that'll make v2.2.1 stop working so that's something
